source 'https://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3'
gem 'sinatra', git: 'https://github.com/sinatra/sinatra.git'
gem 'thin'
gem 'require_all'
gem 'shotgun'
gem 'tux'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'sinatra-twitter-bootstrap', :require => 'sinatra/twitter-bootstrap'
gem 'capybara'